services:
  - type: web
    name: medical-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run medical_bot.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: MODEL
        sync: false
      - key: REPO_ID
        sync: false
